# Generated by Django 3.2.3 on 2021-08-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0005_socialaccount_coach_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('speech_score', models.TextField(default='null', max_length=4, null=True)),
                ('face_score', models.TextField(default='null', max_length=4, null=True)),
                ('article_score', models.TextField(default='null', max_length=4, null=True)),
                ('total_word', models.IntegerField(default=0, null=True)),
                ('total_score', models.TextField(default='null', max_length=4, null=True)),
                ('user_have', models.ManyToManyField(related_name='achievement_have', to='login.SocialAccount')),
            ],
            options={
                'db_table': 'achievement',
            },
        ),
    ]
