# Generated by Django 3.2.3 on 2021-08-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='article_score',
            field=models.CharField(default='null', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='face_score',
            field=models.CharField(default='null', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='speech_score',
            field=models.CharField(default='null', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='total_score',
            field=models.CharField(default='null', max_length=4, null=True),
        ),
    ]
