# Generated by Django 3.2.3 on 2021-08-09 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_auto_20210809_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='user_have',
        ),
    ]
