# Generated by Django 3.2.3 on 2021-08-09 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_userachievement'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userachievement',
            table='user_achievement',
        ),
    ]
