# Generated by Django 3.2.3 on 2021-08-09 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0005_alter_userachievement_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('time', models.IntegerField()),
                ('achievement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='achievements.achievement')),
            ],
            options={
                'db_table': 'grade',
            },
        ),
    ]
