# Generated by Django 3.2.3 on 2021-08-09 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_socialaccount_coach_gender'),
        ('achievements', '0006_gradeachievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='achievements.gradeachievement')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.socialaccount')),
            ],
            options={
                'db_table': 'user_grade',
            },
        ),
    ]
