# Generated by Django 3.2.3 on 2021-08-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0007_usergrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='userachievement',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
