# Generated by Django 3.2.3 on 2021-08-10 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0008_userachievement_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userachievement',
            name='created',
        ),
    ]
