# Generated by Django 3.2.3 on 2021-08-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0009_remove_userachievement_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='userachievement',
            name='created_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='usergrade',
            name='created_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
