# Generated by Django 3.2.3 on 2021-08-17 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0008_socialaccount_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pretest_db', models.FloatField(null=True)),
                ('avg_db', models.FloatField(null=True)),
                ('stop_too_long_score', models.IntegerField(null=True)),
                ('weird_sound_score', models.IntegerField(null=True)),
                ('voice_calm_score', models.IntegerField(null=True)),
                ('frequency_score', models.IntegerField(null=True)),
                ('amplitude_score', models.IntegerField(null=True)),
                ('Overall_score', models.IntegerField(null=True)),
                ('analyze', models.CharField(max_length=250, null=True)),
                ('feedback', models.CharField(max_length=250, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.socialaccount')),
            ],
            options={
                'db_table': 'sound',
            },
        ),
    ]
