# Generated by Django 3.2.3 on 2021-08-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='rank',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
