# Generated by Django 3.2.3 on 2021-08-18 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0002_sound_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sound',
            old_name='Overall_score',
            new_name='overall_score',
        ),
    ]
