# Generated by Django 3.2.3 on 2021-08-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0003_rename_overall_score_sound_overall_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='analyze_json',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='sound',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
