# Generated by Django 3.2.3 on 2021-05-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='family_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='given_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='locale',
            field=models.CharField(default='zh-TW', max_length=200),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='picture',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
