# Generated by Django 3.2.3 on 2021-05-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210523_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
