# Generated by Django 3.2.3 on 2021-08-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_socialaccount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
