# Generated by Django 3.2.3 on 2021-08-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_socialaccount_coach_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
