# Generated by Django 3.2.3 on 2021-08-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_socialaccount_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='total_word',
            field=models.IntegerField(default=0),
        ),
    ]
