# Generated by Django 3.2.3 on 2021-08-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_socialaccount_total_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='initial',
            field=models.BooleanField(default=False),
        ),
    ]
