# Generated by Django 3.2.3 on 2021-07-29 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(default=None, null=True, upload_to='upload')),
                ('fulltext', models.TextField()),
                ('text_len', models.IntegerField()),
                ('pure_text_len', models.IntegerField()),
                ('redundant_1_count', models.IntegerField()),
                ('redundant_2_count', models.IntegerField()),
                ('redundant_3_count', models.IntegerField()),
                ('redundant_4_count', models.IntegerField()),
                ('joy_score', models.FloatField()),
                ('trust_score', models.FloatField()),
                ('surprise_score', models.FloatField()),
                ('anticipation_score', models.FloatField()),
                ('fear_score', models.FloatField()),
                ('sadness_score', models.FloatField()),
                ('anger_score', models.FloatField()),
                ('disgust_score', models.FloatField()),
                ('total_score', models.FloatField()),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=200)),
                ('sentiment', models.CharField(max_length=200)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articleDetails', to='article.article')),
            ],
            options={
                'db_table': 'article_detail',
            },
        ),
    ]
