# Generated by Django 3.2.3 on 2021-07-29 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='audio_file',
        ),
    ]
