# Generated by Django 3.2.3 on 2021-07-29 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_socialaccount_name'),
        ('article', '0002_remove_article_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_account', to='login.socialaccount'),
        ),
    ]
