# Generated by Django 3.2.3 on 2021-08-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='suggest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='talk_speed',
            field=models.FloatField(null=True),
        ),
    ]
