# Generated by Django 3.2.3 on 2021-08-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210803_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rank',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
