# Generated by Django 3.2.3 on 2021-08-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='suggest_json',
            field=models.JSONField(null=True),
        ),
    ]
