# Generated by Django 3.2.5 on 2021-08-10 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateDatetime', models.DateTimeField(auto_now_add=True)),
                ('VideofileName', models.CharField(max_length=50)),
                ('Videofile', models.FileField(upload_to='video')),
                ('AvgEyebrowHeight', models.CharField(default='null', max_length=50)),
                ('AvgEyebrowPitch', models.CharField(default='null', max_length=50)),
                ('AvgMouthHeight', models.CharField(default='null', max_length=50)),
                ('AvgMouthPitch', models.CharField(default='null', max_length=50)),
                ('EyebrowHeight_PR', models.CharField(default='null', max_length=50)),
                ('EyebrowPitch_PR', models.CharField(default='null', max_length=50)),
                ('Mouth_PR', models.CharField(default='null', max_length=50)),
                ('WinkTime', models.CharField(default='null', max_length=50)),
                ('DistractTime', models.CharField(default='null', max_length=50)),
                ('Total_Score', models.CharField(default='null', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_account_to_face', to='login.socialaccount')),
            ],
            options={
                'db_table': 'face',
            },
        ),
    ]
