# Generated by Django 3.2.5 on 2021-08-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facemodel',
            name='Suggest',
            field=models.JSONField(default='null'),
        ),
    ]
