# Generated by Django 3.2.3 on 2021-08-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0002_facemodel_suggest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facemodel',
            name='Suggest',
            field=models.JSONField(null=True),
        ),
    ]
