# Generated by Django 3.2.3 on 2021-08-18 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0003_rename_overall_score_sound_overall_score'),
        ('records', '0002_alter_record_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='sound',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sound.sound'),
        ),
    ]
