# Generated by Django 3.2.3 on 2021-08-19 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0003_alter_facemodel_suggest'),
        ('records', '0003_record_sound'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='face',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='face.facemodel'),
        ),
    ]
