# Generated by Django 3.2.5 on 2021-08-10 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PretestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VideofileName', models.CharField(max_length=50)),
                ('Videofile', models.FileField(upload_to='prevideo')),
                ('PreEyebrowHeight', models.CharField(default='null', max_length=50)),
                ('PreEyebrowPitch', models.CharField(default='null', max_length=50)),
                ('PreMouthHeight', models.CharField(default='null', max_length=50)),
                ('PreMouthPitch', models.CharField(default='null', max_length=50)),
                ('PreEyesPitch', models.CharField(default='null', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_account', to='login.socialaccount')),
            ],
            options={
                'db_table': 'pretest',
            },
        ),
    ]
