# Generated by Django 3.2.3 on 2021-08-19 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_socialaccount_initial'),
        ('pretest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretestmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.socialaccount'),
        ),
    ]
