# Generated by Django 3.2.3 on 2021-08-31 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretest', '0002_alter_pretestmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretestmodel',
            name='Gender',
            field=models.CharField(default='M', max_length=50),
        ),
        migrations.AddField(
            model_name='pretestmodel',
            name='PreSoundAvg',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='pretestmodel',
            name='PreSoundFreq',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='pretestmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
